export {
  type QrResponse,
  type AuthResponse,
  type NotificationResponse,
  type BackendPaginationResponse,
  type PaginationResponse,
  type NotificationConfigRequest,
  type NotificationConfigResponse,
  type EmailConfigRequest,
  type EmailConfigResponse,
  type EmailLayoutConfigRequest,
  type EmailLayoutConfigResponse,
  type UserProfileResponse,
  type UserResponse,
  type RoleResponse,
  type PermissionResponse,
  type RoleRequest,
  type UserRoleUpdaterRequest,
  type PermissionRequest,
  type UserUpdateRequest,
  type ActionResponse,
  type ActionItemWithDependenciesResponse,
  type TaskConfigActionsResponse,
  type FormFieldResponse,
  type FormResponse,
  type TaskConfigActionSave,
  type TaskConfigSaveRequest,
  type TaskConfigListItem,
  type ApplicationResponse,
  type ApplicationClientResponse,
  type ApplicationFindResponse,
  type StateResponse,
  type CityResponse,
  type AddressResponse,
  type NotaryOfficeResponse,
  type AddressRequest,
  type NotaryOfficeRequest,
  type NotaryOfficeUpdateRequest,
  type ApplicationReceivedResponse,
  type AuthSessionResponse,
  type DeviceFcmTokenInfo,
  type UserSessionResponse,
  type CoverageAreaResponse,
  type CoverageAreaRequest,
  type RegionResponse,
  type RegionRequest,
  type RegionUpdateRequest,
  type FranchiseResponse,
  type FranchiseRequest,
  type FranchiseUpdateRequest,
} from '../types/dto';

import type { ApiRepository } from '../repositories/api.repository';
import { HttpApiAdapter } from '../adapters/http-api.adapter';

export function createApiService(baseUrl: string): ApiRepository {
  return new HttpApiAdapter(baseUrl);
}
